# Generated by Django 4.1.4 on 2022-12-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_hit_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='hit',
            name='success',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hitstatus'),
            preserve_default=False,
        ),
    ]
