# Generated by Django 4.1.4 on 2022-12-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hit_description_hit_success'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='success',
            new_name='status',
        ),
    ]
